export const PLANTS = [
  { value: "0001", label: "Werk 0001" },
  { value: "0003", label: "Plant 0003 (is-ht-sw)" },
  { value: "1000", label: "Scrapyard" },
  { value: "1001", label: "SMS1" },
  { value: "1002", label: "SMS2" },
  { value: "1003", label: "WRM" },
  { value: "1004", label: "BRIGHT BAR HEX AND  SQUARE" },
  { value: "1005", label: "AP - Don't use" },
  { value: "1006", label: "RMD-G2" },
  { value: "1007", label: "Wire" },
  { value: "1008", label: "Flange" },
  { value: "1009", label: "Press" },
  { value: "1010", label: 'Old Mill 10"' },
  { value: "1011", label: 'RMD 28" Inch' },
  { value: "1012", label: "SRM Rolling Mill" },
  { value: "1013", label: "Profile Process" },
  { value: "1014", label: "Bright Bar" },
  { value: "1015", label: "Fasteners" },
  { value: "1016", label: "SAF Mill Scale -4 Acre" },
  { value: "1017", label: "Slug Crusher  - 25 Acre" },
  { value: "1018", label: "Sludge Drying Plant" },
  { value: "1019", label: "Zurik Scrap" },
  { value: "1021", label: "SS Seamless Pipe Plant" },
  { value: "1023", label: '18"B MILL' },
  { value: "1024", label: '13"B MILL' },
  { value: "1026", label: "Ferro Molly Plant" },
  { value: "1027", label: "Seamless Pilger Plant" },
  { value: "1100", label: "Mumbai Corporate" },
  { value: "1101", label: "Delhi Corporate" },
  { value: "1102", label: "Canteen" },
  { value: "1103", label: "Bellagio" },
  { value: "1104", label: "70 Bungalow" },
  { value: "1106", label: "Tarapur Corporate" },
  { value: "2001", label: "NITYAA PROCESSOR LLP" },
  { value: "2002", label: "NITYA MILL SCALE" },
  { value: "3001", label: "VAISHNO MEGAMOVERS LLP (Shippi" },
  { value: "3002", label: "VMM -Logistic Division TARAPUR" },
  { value: "3003", label: "VMM - Logistic Division - JNPT" },
  { value: "3004", label: "M N R" },
  { value: "4001", label: "Kestrel Aviation Pvt. Ltd." },
  { value: "4002", label: "KAPL - Logistic Division - ICD" },
  { value: "4003", label: "KAPL - Logistic Division - CFS" },
];

export function plantLabel(value) {
  const plant = PLANTS.find((item) => item.value === String(value || ""));
  return plant ? `${plant.value} - ${plant.label}` : value || "";
}
